services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: akschim-app
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      NODE_ENV: "production"
      PRISMA_CLI_BINARY_TARGETS: "debian-openssl-1.1.x"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.akschim.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.akschim.entrypoints=web"
      - "traefik.http.routers.akschim.service=akschim"
      - "traefik.http.services.akschim.loadbalancer.server.port=3000"
    networks:
      - akschim-network
    restart: unless-stopped
    depends_on:
      - traefik

  minio:
    image: minio/minio:latest
    container_name: akschim-minio
    ports:
      - "9000:9000"      # MinIO API port
      - "9001:9001"      # MinIO Console port
    env_file:
      - .env.local
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-storage:/minio_root
    command: minio server /minio_root --console-address ":9001"
    networks:
      - akschim-network
    restart: unless-stopped

  traefik:
    image: traefik:latest
    container_name: akschim-traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    command:
      - --providers.docker=true
      - --providers.docker.network=akschim-network
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --api=true
      - --api.dashboard=true
      - --api.insecure=true
      - --log.level=INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/traefik
    networks:
      - akschim-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`) || Path(`/dashboard`) || Path(`/api`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=web"

networks:
  akschim-network:
    driver: bridge

volumes:
  minio-storage: