version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: akschim-app
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      NODE_ENV: "production"
      PRISMA_CLI_BINARY_TARGETS: "debian-openssl-1.1.x"
    networks:
      - akschim-network
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: akschim-minio
    ports:
      - "9000:9000"      # MinIO API port
      - "9001:9001"      # MinIO Console port
    env_file:
      - .env.local
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-storage:/minio_root
    command: minio server /minio_root --console-address ":9001"
    networks:
      - akschim-network
    restart: unless-stopped

networks:
  akschim-network:
    driver: bridge

volumes:
  minio-storage: